### PR TITLE
Fix details drawer a11y

### LINKED ISSUE #142: VoiceOver iOS users must double-click to close details drawer

### PR DESCRIPTION
**Pull request by dengeist**
Primarily closes #142

### CODE REVIEW

File: drawer/markup-kit/gulpfile.js [hunk 1]
```diff
@@ -2,12 +2,10 @@ const gulp = require('gulp'),
   sass = require('gulp-sass'),
   postcss = require('gulp-postcss'),
   autoprefixer = require('autoprefixer'),
-  cssnano = require('cssnano'),
-  sourcemaps = require('gulp-sourcemaps');
```
Comment (davodey) [inline drawer/markup-kit/gulpfile.js]: we need to rip this out everywhere.
